### PR TITLE
Main additon

### PR DESCRIPTION
**Pull request by katherineanne21**
Attempted to include the temp data in the main. Wasn't sure how we wanted to store it so feel free to change that and fix any issues you see.

### CODE REVIEW

**Review by mdietze — CHANGES_REQUESTED** [review]
Please do not include Rdata objects in Pull Requests, just code!  More generally, never include anything that's generated/regenerated by you code in your git repository (input files, output files, graphs, etc.)

**Comment by katherineanne21** [comment]
My bad! Can I delete those from this pull request or do I need to create another?

**Comment by mdietze** [comment]
You can delete the files from this PR. The first thing I'd try would be to go to the "Files Changed" tab on the PR and then click on the ... in the top right next to each file and see if "Delete File" is allowed (it's greyed out for me, but since you opened the PR it might work for you). If no, go back to your laptop and at the command line run `git rm <filename>` on each file. For larger files there's a more complicated option that also purges their original commit from the repository (to avoid file bloat) but each of these look small enough to not worry about.

**Comment by katherineanne21** [comment]
Alrighty, now it's fixed

**Pull request merged**
